### ISSUE TITLE
Delete selected Image?

### ISSUE THREAD

**Issue by ghost** [alanpich/tveasyupload#3]
Hi, great add-on!

Could there be a way to reset the value to _empty_, once you have selected an image? As of now you can only replace image with another image.

Simplest way would probably be to do it like a regular image tv: have an editable textfield for value. Then you can just delete value manually?

**Comment by alanpich** [comment]
Try the little green 'reset' icon next to the TV name ;)

(you might need to save and refresh the page before it appears)

**Comment by ghost** [comment]
I hang my head in shame. Didn't get that. All is well.
Thanks.
I was waiting for this tv input type. Great.
