### ISSUE TITLE
Integration of Simple File Upload and MIGX

### ISSUE THREAD

**Issue by ghost** [alanpich/tveasyupload#4]
I'm trying to use SFU inside a MIGX TV. The 'select file' button is displayed and functional, so that the system file select dialogue is activated. After selecting a file, there is a JS error message like this:

Zeitstempel: 19.09.2012 21:26:31
Fehler: TypeError: this.config is undefined
Quelldatei: http://example.com/manager/min/index.php?f=/manager/assets/modext/core/modx.localization.js,/manager/assets/modext/util/utilities.js,/manager/assets/modext/core/modx.component.js,/manager/assets/modext/widgets/core/modx.panel.js,/manager/assets/modext/widgets/core/modx.tabs.js,/manager/assets/modext/widgets/core/modx.window.js,/manager/assets/modext/widgets/core/modx.tree.js,/manager/assets/modext/widgets/core/modx.combo.js,/manager/assets/modext/widgets/core/modx.grid.js,/manager/assets/modext/widgets/core/modx.console.js,/manager/assets/modext/widgets/core/modx.portal.js
Zeile: 64

I wouldn't know if this is a MIGX issue or a SFU issue. As i usually don't have any problems with inputTVs in MIGX, i opened an issue here.

**Comment by alanpich** [comment]
Sounds like an issue with the inputRender not being fully loaded by MIGX. Will definitely be something to be resolved in SFU, i'll take a look asap

**Comment by ghost** [comment]
Hi Alan,
i just tried to use your TV again in a MIGX setup. I used the newest versions of both TVs. There is still a JS error.
I never tried after you closed this issue, so i don't know if it worked then. Is this a new issue?

**Comment by alanpich** [comment]
Unfortunately I thinks its the same old issue. I spoke to Bruno17 a while back and he wasn't able to shine any light on the matter. I'm not sure if it's specific to SFU, or an issue between MIGx and any custom TV class. If that's the case, I'm not sure what can be done to remedy the problem.

I've got one longshot idea that may work... it may be related to the output render template used by SFU. If i get some time over the christmas break I will try and refactor the render into a 100% Ext component and see how that fares.

Sorry I can't be more positive with my response!

**Comment by ghost** [comment]
Thanks, Alan, for taking the time to work on this. It is very much appreciated!
